### PR TITLE
Fixes for newer version of GHC.

### PR DESCRIPTION
**Pull request by sighingnow**

### CODE REVIEW

**Comment by portnov** [comment]
Hello.
The problem was with older version of package?

**Comment by sighingnow** [comment]
This pr fixes two problems: one is for the `monad-control-exception` package, which has been fixed by https://github.com/pepeiborra/control-monad-exception/pull/10, another is that `PutM` is no long an instance of `MonadFail` any more and the `fail` method is not available.

**Comment by portnov** [comment]
ok.

**Comment by sighingnow** [comment]
Thanks for merging!

**Pull request merged**
